deployment:
  tasks:
    # 1. Define a pasta de destino (ajuste 'SEU_USUARIO')
    - export DEPLOYPATH=/home1/thia8868/public_html

    # 2. Instala dependências do PHP (Composer)
    # Nota: O caminho /usr/local/bin/composer é o padrão, mas pode variar conforme a hospedagem
    - /usr/local/bin/composer install --no-dev --optimize-autoloader

    # 3. Instala dependências do Node e gera o Build (Inertia/Vite)
    # Nota: Pode ser necessário usar o caminho completo do npm ou configurar o Node no cPanel antes
    - npm install
    - npm run build

    # 4. Copia a pasta 'public' gerada para a public_html
    # O comando -u copia apenas se o arquivo for novo ou atualizado
    - /bin/cp -R public $DEPLOYPATH
